spring:
  application:
    name: "message2"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
    kafka:
      binder:
        brokers:
          - localhost:9092
server:
  port: 8084