spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8180/realms/master/protocol/openid-connect/certs"
server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"

